languageCode = "en-us"
title = "demize's site"
baseURL = "https://demize.unstable.systems/"
theme = "beautifulhugo"
enableGitInfo = true

[permalinks]
    post = "/:year/:month/:day/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/demize"
[[menu.main]]
    name = "Contact"
    url = "/contact/"
[[menu.main]]
    name = "Keybase"
    url = "https://keybase.io/demize"
[params]
    description = "demize posts stuff here sometimes"
    author = "demize"
    logo = "/images/avatar.png"
    enableGitInfo = true
    commit = "https://github.com/demize/site/tree/"

[Author]
name = "demize"
github = "demize"
twitter = "demize95"
mastodon = "unstable.systems/@demize"
