languageCode = "en-us"
title = "demize's site"
baseURL = "https://demize.unstable.systems/"
theme = "indigo"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/demize"
[[menu.main]]
    name = "Contact"
    url = "/contact/"
[[menu.main]]
    name = "Keybase"
    url = "https://keybase.io/demize"
[params]
    description = "demize posts stuff here sometimes"
    author = "demize"
    Avatar = "/images/avatar.jpg"
